#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七

bspc config border_width 1.5
bspc config window_gap 7

bspc config split_ratio 3
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv state=floating


# Wallpaper
#feh --bg-scale ~/Imágenes/Wallpapers/fav/11.jpg
feh --randomize --no-fehbg --bg-fill ~/Imágenes/Wallpapers/fav/

# Polybar
# /home/jose/polybar-collection/launch.sh

#Picom
picom -b &
